### ISSUE TITLE
Omit optional values if they are empty

### ISSUE THREAD

**Issue by alexander-demichev** [fusor/cpma#169]
We should omit optional values if they are empty. For example:
```
identityProviders:
  - name: my_remote_basic_auth_provider 
    challenge: true 
    login: true 
    mappingMethod: claim 
    provider:
      apiVersion: v1
      kind: BasicAuthPasswordIdentityProvider
      url: https://www.example.com/remote-idp 
      ca: /path/to/ca.file # OPTIONAL
      certFile: /path/to/client.crt  # OPTIONAL
      keyFile: /path/to/client.key # OPTIONAL
```
certFile, ca and keyFile can be empty and we should not generate secrets and have them in translated CR.
