### ISSUE TITLE
Namespace Rank

### ISSUE THREAD

**Issue by jmontleon** [fusor/cpma#253]
Add a field to the Namespace report with quantity 

This will involve some research to determine to what extent this is possible. 

It may be that the best we can do is see what's requested by pods in the namespace. It looks like pods can be set up without resource requests in which case it just shows `resources: {}`

```
resources:
  requests: 
    cpu: "100m"
    memory: "256Mi"
```

This may involve looking at the pods to determine 
- [ ] CPU
- [ ] Memory
- [ ] Pods (Quantity)
