### ISSUE TITLE
Tool shouldn't create manifests for configurations that don't exist

### ISSUE THREAD

**Issue by dymurray** [fusor/cpma#77]
I don't have any oauth or secret configurations in my ocp3 config, and that led to manifests being created that have empty data.

```
[dymurray@pups cpma]$ cat data/manifests/100_CPMA-cluster-config-oauth.yaml 
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
  namespace: openshift-config
spec:
  identityProviders:
  - null
[dymurray@pups cpma]$ 
[dymurray@pups cpma]$ ls data/manifests/
100_CPMA-cluster-config-oauth.yaml    100_CPMA-cluster-config-secret-.yaml  
[dymurray@pups cpma]$ cat data/manifests/100_CPMA-cluster-config-secret-.yaml 
apiVersion: ""
kind: ""
type: ""
metadata:
  name: ""
  namespace: ""
data: null
```

We should have some better error checking so that we aren't creating null manifests.
